### ISSUE TITLE
Linux VBox problems

### ISSUE THREAD

**Issue by Sweedify** [conan513/SingleCore_TC#19]
Hey again, and great release! Got it working after a little bit of a hassle since i only have a mobile 4G at hand.

However there are couple broken things...

1) npcbots crashing the server in numerous different ways. example when you have spawned the bots and run away from them OR teleporting via teleporter OR when you queue to random dungeon with them.

2) npcbot doesnt show equipment on them (or is this a upcoming feature?)

3) I cant access the VBox folders to change settings in example world.conf or bots.conf at all

Thanks for the effort @conan513 ! This is going to be the best project ever when you get it all clicked !

ps. What do you think about Ryms bg script? Could it be possible to manipulate or use it somehow to make arena work like battlegrounds work with it? I need dem arenapoints :+1:

**Comment by thesawolf** [comment]
@Sweedify 
1. I recently did a commit https://github.com/thesawolf/TrinityCore/commit/ba8738edaf5a274dd05973fb3dcf09bfbc47005f
   that should (hopefully) resolve this. I tested it multiple times running around zones at 10.0 speeds (flew off a hill and killed myself too running at the mach speed since I forgot to .gm on) and I teleport hopped to various zones and the NPCBot kept up without any problems or crashes. Not sure when/if Conan got it added into SingleCore.
2. NPCBots use npc ModelIDs and will never show any gear aside from the preset look for that model. The only appearance you can affect without a database change to their world.creature_template or the world.create_template_outfits is anything placed in their hands (ie. weapons, staves, shields, etc.)
3. Can't help you there.

**Comment by snomann72** [comment]
The settings for the world and bots is setup-world and setup-bots.  You can type in "commands" to get a list of the current commands on that page.
