### ISSUE TITLE
A bit of a stupid question but...

### ISSUE THREAD

**Issue by sout12** [conan513/SingleCore_TC#30]
Could you ever make bots like talk ? Like "Mana is low" stuff like that? And would you be able to do a command to make a bot talk and it says whatever you want it to say? Like .bot say "text"

**Comment by thesawolf** [comment]
I know that my Playerbots spam the hell out of me when I'm in a dungeon with them with mana is low, health is low, etc. messages.. to the point I need to look and see what I can do to lessen that a bit. But otherwise, they are set to do so in various percentage situations. I know some of the conditions for when to say them are in one of the tables in the characters dbase.

The playerbots are actually coded with taunts, loot says, etc with about 200 something phrases. I just don't think they are activated. You can see some of them in some aiplayerbot_speech tables in the characters database.

**Comment by sout12** [comment]
How do i active them, in the ai_playerbot_speech_probability and set it all to 100?

**Comment by thesawolf** [comment]
There is currently no setting for them.

**Comment by sout12** [comment]
Aw :(
