### ISSUE TITLE
My Ac-web account stolen

### ISSUE THREAD

**Issue by conan513** [conan513/SingleCore_TC#36]
Please nobody download anything from my SPP threads on AC web! Someone stolen my account and posting infected files!

**Comment by wrathix** [comment]
Horrible people omg :(
Thanks for the heads up, did a scan and turn up nothing detected from the 923MB update.
Was that one really your update, as the bots were working normally again and resurrecting as they should :]

(Rubix)

**Comment by sout12** [comment]
Yea, my whole pc is fucked. I have to reformat now god dam it. Great...
And he stole my fucking account as well. On Ac-web. My account was "Sout12" same on here  :P 
Whoever does this needs to fucking burn in hell alive. Why does people do this shit
I am posting this from a friends laptop. 
Things that happened 
1) Jeff the killer popped up on screen i turned off pc
2) Cmd randomly started opening i turned off pc
3) Webcam randomly turned on as well
4) Random shit opened up and i try'd to virus scan and it fking closed.
I am fking pissed man
Is their no way to remove it ? 
IF HE POST ANYTHING ON ACWEB AS "SOUT12" IT WAS NOT ME!

**Comment by wrathix** [comment]
@sout12 For me it went away after restarting the pc. Have you tried turning it on and just continuing like you normally would?

**Comment by sout12** [comment]
@wrathix Yea, i have unplugged the internet on my PC and now it seems to not be popping up but idk
I am now running Malware

**Comment by wrathix** [comment]
@Update your malwarebytes and do a scan I suppose would work

**Comment by sout12** [comment]
@wrathix Its free right? Like it will remove it if it can ?

**Comment by wrathix** [comment]
yeah but maybe this is a new virus so try going to malwarebytes.com and updating

**Comment by thesawolf** [comment]
Yes.. MalwareBytes has a free version. Get it and use it quickly before whatever you have embeds itself more.

**Comment by conan513** [comment]
Please report my acweb account to admins, I love the community there and don't want to anyone get fucked with this asshole files.

If you downloaded anything on the last day, I highly recommend to install a professional antivirus like bitdefender or kaspersky to find all infected files on your PC.

**Comment by sout12** [comment]
My AC-web account is still stolen, can i do a email reset kinda thing?

**Comment by sout12** [comment]
Okay, i think that its removed thank the lord.
My webcam is not turned on no popups nothing :D 
Acweb account is still stolen though but, i rather have my PC back any day :P 
I'm just gonna make a new account with the name "Sout122" with another password
Does the email activation take a while to receive ? 
Can i not register with a gmail email? it says "Invalid Redirect URL (https://www.google.com/)"

**Comment by conan513** [comment]
If MalwareBytes working please share it with the others on acweb

**Comment by wrathix** [comment]
Ok, yea the previous postings above by 'Wrathix'  were not real.  Same guy has my github account then I guess.  Resetting pwd now.

**Comment by wrathix** [comment]
By the way - I found the process it was hiding in.   "Audiodriver.exe"  in the Roamingprofiles folder.
ctrl+alt+del , if you see it there, KILL IT

**Comment by wrathix** [comment]
Heres what the file looks like and where it can be found in the Roaming Profile subfolders
http://oi65.tinypic.com/350sc34.jpg

**Comment by snomann72** [comment]
MalwareBytes is actually free, but you can do the 14 day trial.  The website is really easy to remember too.  https://www.malwarebytes.com.  I also use Adwcleaner.com.  Another useful app to remove excessive issues, like malware, etc....

**Comment by conan513** [comment]
I don't know how do I get this shit. I never using cracked apps (games, programs) except the VS but it's just a serial code.

anyway let's get back to work and find this mysterious source of the "ghost bug"
and I think the vbox version is safe, because no virus or malware for linux

![2sg48nu](https://cloud.githubusercontent.com/assets/459246/16940926/3be0ec20-4d8d-11e6-866c-47a8b722e44c.png)

**Comment by sout12** [comment]
Conan, do you have a link for all the maps? I don't wanna download those files on ACweb 
Can i extract data from the Vbox to my desktop ?
The files are too big to extract :(

**Comment by thesawolf** [comment]
Linux is much less vulnerable to malware and virii, but it does have them occasionally via tainted binaries or malware picked up through bad sites, etc. but I digress. About that "ghost bug".. probably better to move discussion to sout12's reported issue or make a new one. I just noticed on my playerbots that I can't pull up their dead strats with "dead ?" might be the root of the issue in the actions

**Comment by sout12** [comment]
So, nobody has 1.8 updated maps ?

**Comment by oblisgr** [comment]
Hi! Finaly i can speak!!!
In the other forums I was expecting the activation mail like... ever?
Never came.

I was very happy to see that such a project existed. I was feeling that I had bought a game for such ammount of money and it wasnt mine. I had to pay to play with my game. But now i can play finally for free and make my money get value. The game is pretty interesting with the bots though they have some bugs. So... i have some questions if someone want to aswer me.

Sorry so many questions but it was so much time i couldnt ask them.

TRINITYCORE:
- The trinitycore used in SSP is the final version for 3.3.5a? I mean are there any newer version that maybe script more creatures and skills? 
- If it is not the final version, how can I update the core without screwing the SSP?
- Is there any % for what is scripted (zones-instances) in SSP? I remember there was a forum entry for scriptDEV2 in the past that was giving info but i cannot find it anymore.

MANGOSBOT:
-Are there any makro packages to define a bot's behaviour? For example (Druid-Bear, Warrior-Protection)The FAQ i found is not very informative and doesnt give any help about what each flag in CO,NC etc means, and more info in general.
-I for sure cannot make the Druid change into a bear. Has anyone managed to do this? What flags have you used?
-If priest gets the heal flag it stops fighting at all! Is this bug?

GENERAL:
-Can i use any other bot mod? Maybe something less buggy? Do you have any info?
-I want to remove the cheat NPCS in oggrimar. Is this possible? I want my game to be as more blizzlike as it can.

**Comment by sout12** [comment]
Please try to fix this dead bot issue <3 
I wish their was a command to revive all or soemthing

**Comment by thesawolf** [comment]
(oh good lord.. I just realized this got turned into a novella.. sorry folks)
@oblisgr  Not really the best place to ask all those questions. You would probably be better off either opening a "New Issue" with your questions in there or over on ac-web (despite the current hijacking fiasco). Regardless, I'll do what I can to answer some of your questions since Conan has enough issues on his plate atm.

TrinityCore:
1. The core is constantly getting improved upon but it official stops at 3.3.5a (WoTLK content) in that particular branch. There is 6.X (WoD and below) branch currently being developed too but is in a VERY incomplete state.. You should be looking at: https://github.com/TrinityCore/TrinityCore   and http://www.trinitycore.org for more information
2. Conan has been keeping most up-to-date TC commits merged into the SingleCore fork every few days to a week behind the current TC. Beyond that, if you want it kept constantly updated, it would be up to you to fork your own off of Conan's Single core and just set up TrinityCore/3.3.5 branch as your upstream to pull from. 
3. There really isn't an ACCURATE percentage of things complete ANYWHERE (people just like putting up stuff like that). However, as SPP fully uses TC/3.3.5 you can expect about 99-100% completion in pretty much all content (with a few exceptions in WoTLK Champions Trials, etc. ) up to WoTLK. But then again as they say "73.6% of all Statistics are made up." Take those numbers with a grain of salt and know that ALOT is fully functional and working.

MANGOSBOT:
1. I'm actually working on a comprehensive guide for the bots (already finished NPCBots), but the PlayerBot section is still in the works. You can read some of it here in the meantime: https://github.com/thesawolf/TrinityCore/blob/TrinityCoreLegacy/README_Bots.md
But currently, the best documentation for PlayerBots is over here: http://ike3.github.io/mangosbot-docs/
You can setup macros easily enough if you are familiar with the commands (for now). Using party chat can let you mass update strats or roles, while individual tells can clear up some. At the heart you have nc strats that handle regular activities and pre-attack targeting (via something like 'attack weak'). Actual roles and combat strats are handled via co strats (common are 'dps' 'tank' 'heal' with extras like 'dps aoe' 'tank aoe' etc. (you can get an applicable list by saying in party or telling the individual bot 'help'  or getting list of current settings by doing 'nc ?' and 'co ?' Assigning more than one role for a bot "usually "confuses them a bit so avoid overlapping dps, tank and heal. 
There is also a PlayerBotUI addon floating around originally for Mangos and perhaps updated for the latest by someone.
2. Btw.. Druids when set with co +tank will show bear.. this is what is displayed when you have +tank set on a druid.. and cat usually indicates +dps. But you need to turn off other forms/roles. And they usually will change on their own in combat. If not, you can make them manually by telling them looking up 'spells bear' to get the Bear Form link and then tell them cast Bear Form (the linked version.. not verbosely)
3. Once again.. look for role overlaps on the priest to make sure all they have is co heal (and extra defaults).. make sure they also have follow in nc (at least) and no passive

GENERAL:
1. NPCBots should be available in SPP. Use .npcbot to play with those.. they are minion-like bots with limited control.. but they do the job fine until you need more precise control in dungeons, raids. There are no other bot codes out there really. Not working ones at least. And you can find no finer bots than with NPCBots and PlayerBots
2. I'd imagine you can manually delete them as gm with .npc delete (TARGET). Or pull them out of the creature tables in the world databases. If you want blizzlike, SPP will not really be for you. Blizzlike would involve more player involvement and SPP is geared towards... well.. Single Player experience :) If you want true Blizzlike, there are other Blizzlike-specific repacks out there that might be more to your liking. Otherwise, the SPP includes a number of patches to enhance the SPP experience and fill/fix the void of a normally MMO-required world.

Hope that helps. Good luck.

**Comment by thesawolf** [comment]
PrivateDonut posted that links have been removed and account temp banned.
http://www.ac-web.org/forums/showthread.php?221383-Single-Player-Project-TC-R2&p=2236323&viewfull=1#post2236323

**Comment by oblisgr** [comment]
Nice! Can anyone help me get the activation link in these forums?
I cant post anything... :(

**Comment by thesawolf** [comment]
Can't help you there as that's an ac-web thing, sorry. Maybe try to have them resend or make another account with same/different email? Somethings gotta give.

**Comment by sout12** [comment]
http://www.ac-web.org/forums/showthread.php?221383-Single-Player-Project-TC-R2&p=2236253#post2236253
The first post of my own account is not me btw, he hacked my Acweb account too :( just saying
