### ISSUE TITLE
SmartAI

### ISSUE THREAD

**Issue by oblisgr** [conan513/SingleCore_TC#42]
Ok, there are some zones that have quest creature that are not scripted. 
Like the Grimtotem taurens for example in Stonetalon Mountains.
If I use the SmartAI, shall I be able to add the missing spells and a basic AI for them to use them?
There is a single video in youtube and I cant even hear what the dude says.

**Comment by thesawolf** [comment]
Actual blizz content is something the TC team usually works on since they have sniffs to backup details. If you know of some specific missing content, I'd recommend opening an issue with them and pointing it out. They are the ones that try to keep the core as blizzlike as possible. Seeing as how I haven't played on live in several years, I wouldn't know the whole scripted setup for any missing content you find. SmartAI scripts fun to work with (sarcasm). I think I know the video you are talking about and yeah.. lots of mumbling. If I find another resource to point you in the right direction, I'll post it here later.
