### ISSUE TITLE
LFG and NPCBot issue

### ISSUE THREAD

**Issue by snomann72** [conan513/SingleCore_TC#47]
I found 3 issues so far with the LFG and NPCBots porting and Gearing NPCs.  Here is what is going on.

The LFG System is ok.  Completing the dungeon is good.  Have not died in the dungeon.  Once you finish the dungeon with the NPCBots, you cannot exit the dungeon, as in finish the dungeon after exiting.  The only workaround to getting the LFG icon to disappear is by exiting the game and restarting wow.

The NPCBots porting to you when you either fly from the flight path, Hearthstone to your save point, and even logging in tot he game.  I have proof that the issue been happening quite alot since the bots were added. 

http://i.imgur.com/cNBoCJv.jpg

The last piece of info I have found is gearing the NPCBots.  When gearing the NPCBots, the buttons that you select to gear them from the items is unresponsive at times.  Closing out and reopening the Gear feature fixes it, but do need to be worked on.

**Comment by thesawolf** [comment]
I responded to your post on ac-web regarding 2 of your issue reports here. Cannot access your Google drive link. Try uploading your pic to imgur or gyazo so I can see what you are referring to since I cannot seem to replicate it the way you are reporting.

I'll look into the LFG icon thing after a dungeon is done as I believe I have seen that too.

As for gearing, I'll check the gossip menus and see if I can find out what you are referring to.

**Comment by snomann72** [comment]
I am posting 3 more pictures of the NPCBots.  Also, I found a interesting tidbit on the Worldserver Log File.  There are 4 SQL Errors when having the NPCBots in the group.  All the pictures shows the npcbots are online, but the chat text says they are offline.

[NPCBots Logging In.](http://i.imgur.com/7CTyc1e.jpg)
[NPCBots showing they are on, but chat text is saying they are not online.](http://i.imgur.com/0BSJY4i.jpg)
[NPCBots zoned and on Mounts, but chat text is shows they are offline](http://i.imgur.com/PoIEFaO.jpg)

I do know that it takes a few seconds for them to login, which isn't a issue.  Wanted to bring it forward so it can be checked.

I found 4 errors containing the NPCBots.  It shows in the DB.  Here is what the errors state.

`SQL(p): INSERT INTO group_member (guid, memberGuid, memberFlags, subgroup, roles) VALUES(1, 120, 0, 0, 0)
 [ERROR]: [1062] Duplicate entry '120' for key 'PRIMARY'`
`SQL(p): INSERT INTO group_member (guid, memberGuid, memberFlags, subgroup, roles) VALUES(1, 121, 0, 0, 0)
 [ERROR]: [1062] Duplicate entry '121' for key 'PRIMARY'`
`SQL(p): INSERT INTO group_member (guid, memberGuid, memberFlags, subgroup, roles) VALUES(1, 119, 0, 0, 0)
 [ERROR]: [1062] Duplicate entry '119' for key 'PRIMARY'`
`SQL(p): INSERT INTO group_member (guid, memberGuid, memberFlags, subgroup, roles) VALUES(1, 118, 0, 0, 0)
 [ERROR]: [1062] Duplicate entry '118' for key 'PRIMARY'`

I also found a new script info, but the script itself is missing.
`[Condition SourceType: 15 (Gossip Menu Option), SourceGroup: 50000, SourceEntry: 1, ConditionType: 6 (Team)] specifies unknown team (0), skipped.
ScriptName 'momcat' exists in database, but no core script found!`

**Comment by thesawolf** [comment]
The momcat script is in my branch and I'm guessing Conan didn't move that over to his since it was an early attempt at me making a catalogue to hire NPCBots that I abandoned since I'm redoing the .npcbot lookup to mimic what I did with the .bot lookup (for PlayerBots). You can ignore that error, it's harmless.

As for the group insertions, the duplicate entries look like the messages you would receive after you've logged back in or they go offline due to out of range and they try to reassert the group (hence the duplicate entry messages). It's more or less a harmless set of errors. I'll look at the grouping code tho so maybe we can reduce the error output and leave REAL errors for the DBErrors.log.

And I've already talked about the offline thing for groups while you are travelling in the ac-web thread.

**Comment by snomann72** [comment]
I noticed 1 issue when I get those Errors, My system crash with a Segmentation Fault Crash.  And that was from my Blood Elf.  Could not continue due to that crash.

The tank logs in and whisper Hi there, or something to that, and sit for 30 seconds and get hit with the Segmentation Fault Crash.
