### ISSUE TITLE
Bots using the mass buff

### ISSUE THREAD

**Issue by sout12** [conan513/SingleCore_TC#53]
Will bots ever be able to use the mass buff? The spell where it just buffs everyone ?

**Comment by thesawolf** [comment]
Please refrain from asking these "will bots ever..." questions you seem fond of posting. 

I'm going to answer ALL your current and future "will bots ever.." questions. 

**.... IF SOMEONE CODES IT...** 

seriously, I'm not trying to be mean. That line of questioning is tedious. If they don't do something already, chances are they won't until someone can take the time to code it in. Alot of programming goes into making Bots act the way they do already and to make them function with gear, interactions, spells, etc. Some things just haven't made there way into coding them, others might be hard. I know adding in the warlock stones/soulwell and the mages food/drink/table/portals for the NPCBots was frustrating for me, but it was doable. 

If a mass buff is available as a spell, chances are a PlayerBot might be able to do it if you do 'spells NAMEOFBUFF' and see it on the list. If it's there you do 'cast NAMEOFBUFF-LINK' (when I say link, you need the spell link from the listing copypasta into the chat for them to cast it. Hopefully, it should work since you are just triggering a manual spell cast for that Bot. An NPCBot would have to be coded to do the spell. (they are already coded to a point to handle some spells and abilities.. just check their "Abilities..." gossip option to see if it's available and they are at the level to do it.
